### Update-Patient
PUT http://lb-1a45b592.elb.localhost.localstack.cloud:8080/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "Vineet pareek new",
  "email": "vineet@gmail.com",
  "address" : "12 borderland germany",
  "dateOfBirth" : "1990-09-08"
}