spring.application.name=billing-service

server.port=4001
grpc.server.port=9001

# ===============================
# Actuator / Health
# ===============================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# ===============================
# Tracing (OpenTelemetry + Zipkin)
# ===============================
management.tracing.sampling.probability=1.0
management.opentelemetry.logging.export.otlp.endpoint=http://otel-collector:4318/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4318/v1/traces
management.otlp.metrics.export.enabled=false

# Enable Kubernetes-style probes
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
