spring.application.name=patient-service
server.port=4000

# ===============================
# Database
# ===============================
#spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
#spring.datasource.username=admin_user
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# ===============================
# Billing gRPC
# ===============================
billing.service.address=localhost
billing.service.grpc.port=9001

# ===============================
# Logging
# ===============================
logging.level.root=info
