spring.application.name=patient-service
server.port=4000

# ===============================
# Database
# ===============================
#spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
#spring.datasource.username=admin_user
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# ===============================
# Billing gRPC
# ===============================
billing.service.address=localhost
billing.service.grpc.port=9001

# ===============================
# Actuator / Health
# ===============================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.kafka.enabled=true

# ===============================
# Tracing (OpenTelemetry + Zipkin)
# ===============================
management.tracing.sampling.probability=1.0
management.opentelemetry.logging.export.otlp.endpoint=http://otel-collector:4318/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4318/v1/traces
management.otlp.metrics.export.enabled=false

# Enable Kafka observation
spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true

# Enable Kubernetes-style probes
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG

