apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: patient.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.gateway.name }}
                port:
                  number: {{ .Values.services.gateway.port }}
