{{- if .Values.deps.zipkin.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: {{.Values.deps.zipkin.image}}
          ports:
            - containerPort: {{.Values.deps.zipkin.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: zipkin
  ports:
    - port: {{.Values.deps.zipkin.port}}
      targetPort: {{.Values.deps.zipkin.port}}
  {{- end}}
